apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: ${name}
spec:
  allowConcurrency: true
  discover:
    find:
      command:
        - find
        - "."
        - -name
        - kustomization.yaml
  generate:
    command:
      - sh
      - "-c"
      - "kustomize build . | argocd-vault-plugin generate -"
  lockRepo: false