apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-avp-kustomization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-avp-kustomization
  template:
    metadata:
      labels:
        app: demo-avp-kustomization
    spec:
      containers:
      - name: demo-avp-kustomization
        image: nginx
        envFrom:
        - configMapRef:
            name: db-config
        - secretRef:
            name: db-secret
