apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-avp-kustomization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-avp-kustomization
  template:
    metadata:
    spec:
      containers:
        - name: demo-avp-kustomization
          image: nginx
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DATABASE_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
